name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Natural language request (e.g., "Deploy a staging PostgreSQL on Azure")'
        required: true

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq (for JSON parsing)
        run: sudo apt-get install -y jq

      - name: Generate Terraform using OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          chmod +x scripts/call_openai.sh
          ./scripts/call_openai.sh "${{ github.event.inputs.prompt }}"

      - name: Initialize Terraform
        working-directory: infra/staging
        run: terraform init

      - name: Apply Terraform
        working-directory: infra/staging
        run: terraform apply -auto-approve
