name: Terraform Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/infra/staging/main.tf'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init
      working-directory: scripts/infra/staging

    - name: Terraform Plan
      run: terraform plan
      working-directory: scripts/infra/staging

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: scripts/infra/staging
