name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'infra/staging/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0  # Optional: Set your version

      - name: List contents for debugging
        run: ls -R
        working-directory: infra/staging

      - name: Terraform Init
        run: terraform init
        working-directory: infra/staging

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/staging
